
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

PATH="/opt/local/bin:${PATH}"
# Initialization for FDK command line tools.Tue May 28 01:59:43 2013
FDK_EXE="/Users/wuyexiong/bin/FDK/Tools/osx"
PATH=${PATH}:"/Users/wuyexiong/bin/FDK/Tools/osx"
export PATH
export FDK_EXE
