source ~/.zsh/checks.zsh
source ~/.zsh/colors.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/bindkeys.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/history.zsh
source ~/.zsh/zsh_hooks.zsh
source ~/.zsh/zprofile
#source ~/.zsh/hitch.zsh
# source /opt/github/env.sh
#zsh theme
plugins=(macports rails3 rails git textmate ruby rvm gem git github brew bundler textmate pow)
export ZSH_THEME="agnoster"
export PATH=/usr/local/bin/npm/bin:$PATH
source  ${HOME}/.dotfiles/z/z.sh
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
