source ~/.zsh/checks.zsh
source ~/.zsh/colors.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/bindkeys.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/history.zsh
source ~/.zsh/zsh_hooks.zsh
source ~/.zsh/zprofile
#source ~/.zsh/zlogin
#source ~/.zsh/hitch.zsh
# source /opt/github/env.sh
#zsh theme
plugins=(macports rails3 rails git textmate ruby rvm gem git github brew bundler textmate pow)
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
#export ZSH_THEME="agnoster"
export ZSH_THEME="wedisagree"
export PATH=/usr/local/bin/npm/bin:$PATH
source  ${HOME}/.dotfiles/z/z.sh
#JavaHome switch
alias java_ls='/usr/libexec/java_home -V 2>&1 | grep -E "\d.\d.\d[,_]" | cut -d , -f 1 | colrm 1 4 | grep -v Home'
function java_use() {
    export JAVA_HOME=$(/usr/libexec/java_home -v $1)
    export PATH=$JAVA_HOME/bin:$PATH
    java -version
}
function mountAndroid { hdiutil attach ~/android.dmg -mountpoint /Volumes/android; }
unsetopt NOMATCH
ulimit -n 8192
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
